version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.local
      args:
        - TZ=${TZ}
    volumes:
      - ./src:/var/www/src
      - ./logs:/var/log/php
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/src
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - "3006:3306"

# Persistence data
volumes:
  db-store:
